title: Emma's Balcony Flower Garden
description: A first-time gardener's journey transforming a sunny Stuttgart balcony into a colorful flower garden.
baseurl: /emmas-gardening-project
url: https://rompasaurus.github.io
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default
